export const REGISTRAR_USUARIO_EXITOSO = 'REGISTRAR_USUARIO_EXITOSO';
export const REGISTRAR_USUARIO_ERROR = 'REGISTRAR_USUARIO_ERROR';

export const CERRAR_SESION = 'CERRAR_SESION';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';